// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBDgV_8L_hgvR6EmrRVrrwqIXEh0-rITE8',
  //   appId: '1:332823018473:ios:93d8fe41dbaf84637ea978',
  //   messagingSenderId: '332823018473',
  //   projectId: 'scout-quest-be321',
  //   storageBucket: 'scout-quest-be321.appspot.com',
  //   iosBundleId: 'com.example.scoutquest',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    authDomain: 'localhost', // Use 'localhost' for the emulator
    apiKey: 'AIzaSyBDgV_8L_hgvR6EmrRVrrwqIXEh0-rITE8',
    appId: '1:332823018473:ios:93d8fe41dbaf84637ea978',
    messagingSenderId: '332823018473',
    projectId: 'scout-quest-be321',
    storageBucket: 'scout-quest-be321.appspot.com',
    // iosBundleId: 'com.example.scoutquest',
  );
}
